In [1]:
import numpy as np

In [3]:
ds = np.array([[-3,-2,0]
              ,[-2,-1,0]
              ,[-2,-2,0]
              ,[-2,-3,0]
              ,[-1,-2,0]
              ,[1,2,1]
              ,[2,1,1]
              ,[2,2,1]
              ,[2,2,1]
              ,[2,3,1]
              ,[3,2,1]])
ds

array([[-3, -2,  0],
       [-2, -1,  0],
       [-2, -2,  0],
       [-2, -3,  0],
       [-1, -2,  0],
       [ 1,  2,  1],
       [ 2,  1,  1],
       [ 2,  2,  1],
       [ 2,  2,  1],
       [ 2,  3,  1],
       [ 3,  2,  1]])

In [4]:
X = ds[:, :-1]
X

array([[-3, -2],
       [-2, -1],
       [-2, -2],
       [-2, -3],
       [-1, -2],
       [ 1,  2],
       [ 2,  1],
       [ 2,  2],
       [ 2,  2],
       [ 2,  3],
       [ 3,  2]])

In [6]:
Xb = np.hstack([np.ones([X.shape[0],1]), X])
Xb

array([[ 1., -3., -2.],
       [ 1., -2., -1.],
       [ 1., -2., -2.],
       [ 1., -2., -3.],
       [ 1., -1., -2.],
       [ 1.,  1.,  2.],
       [ 1.,  2.,  1.],
       [ 1.,  2.,  2.],
       [ 1.,  2.,  2.],
       [ 1.,  2.,  3.],
       [ 1.,  3.,  2.]])

In [23]:
Xb.T

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-3., -2., -2., -2., -1.,  1.,  2.,  2.,  2.,  2.,  3.],
       [-2., -1., -2., -3., -2.,  2.,  1.,  2.,  2.,  3.,  2.]])

In [8]:
Y = ds[:, -1:]
Y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [9]:
W = np.array([[0.1]
             ,[0.2]
             ,[0.3]])
W

array([[0.1],
       [0.2],
       [0.3]])

In [10]:
a = 5
a

5

In [11]:
Z = Xb.dot(W)
Z

array([[-1.1],
       [-0.6],
       [-0.9],
       [-1.2],
       [-0.7],
       [ 0.9],
       [ 0.8],
       [ 1.1],
       [ 1.1],
       [ 1.4],
       [ 1.3]])

In [19]:
Yhat = 1/(1 + np.exp(-Z))
Yhat

array([[0.24973989],
       [0.35434369],
       [0.2890505 ],
       [0.23147522],
       [0.33181223],
       [0.7109495 ],
       [0.68997448],
       [0.75026011],
       [0.75026011],
       [0.80218389],
       [0.78583498]])

In [24]:
YY = Y - Yhat
YY

array([[-0.24973989],
       [-0.35434369],
       [-0.2890505 ],
       [-0.23147522],
       [-0.33181223],
       [ 0.2890505 ],
       [ 0.31002552],
       [ 0.24973989],
       [ 0.24973989],
       [ 0.19781611],
       [ 0.21416502]])

In [25]:
Xb

array([[ 1., -3., -2.],
       [ 1., -2., -1.],
       [ 1., -2., -2.],
       [ 1., -2., -3.],
       [ 1., -1., -2.],
       [ 1.,  1.,  2.],
       [ 1.,  2.,  1.],
       [ 1.,  2.,  2.],
       [ 1.,  2.,  2.],
       [ 1.,  2.,  3.],
       [ 1.,  3.,  2.]])

In [22]:
S = np.dot(Xb.T, (YY))
S

array([[0.0541154 ],
       [5.77695911],
       [5.69883904]])

In [18]:
W = W + ((a/10) * S)
W

array([[0.1541154 ],
       [5.97695911],
       [5.99883904]])