In [3]:
import numpy as np
import pandas as pd

In [4]:
ds = np.array([[1,2],[2,3]])
ds

array([[1, 2],
       [2, 3]])

In [5]:
ds[:,1]

array([2, 3])

In [6]:
ds[:,:1]

array([[1],
       [2]])

In [7]:
ds[:,1:]

array([[2],
       [3]])

In [8]:
ds[1,1]

3

In [9]:
ds[1:,:1]

array([[2]])

In [10]:
ds[:,-1:]

array([[2],
       [3]])

In [79]:
ds2 = np.array([[3,2,3]
               ,[1,2,3]])

In [1]:
ds2

NameError: name 'ds2' is not defined

In [12]:
ds = np.array([[0,0,1]
              ,[1,0,3]
              ,[2,2,11]
              ,[0,1,4]
              ,[1,1,6]
              ,[2,3,14]
              ,[0,2,7]
              ,[1,2,9]
              ,[2,0,5]
              ,[2,1,8]])

In [16]:
ds.shape

10

In [35]:
b = np.ones([ds.shape[0],1])

In [38]:
X = ds[:,:-1]
X

array([[0, 0],
       [1, 0],
       [2, 2],
       [0, 1],
       [1, 1],
       [2, 3],
       [0, 2],
       [1, 2],
       [2, 0],
       [2, 1]])

In [39]:
Y = ds[:,-1:]
Y

array([[ 1],
       [ 3],
       [11],
       [ 4],
       [ 6],
       [14],
       [ 7],
       [ 9],
       [ 5],
       [ 8]])

In [41]:
Xb = np.hstack([b, X])

In [42]:
Xb

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 2.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 2., 3.],
       [1., 0., 2.],
       [1., 1., 2.],
       [1., 2., 0.],
       [1., 2., 1.]])

In [43]:
XbT = Xb.T
XbT

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 2., 0., 1., 2., 0., 1., 2., 2.],
       [0., 0., 2., 1., 1., 3., 2., 2., 0., 1.]])

In [44]:
 (XbT.dot(Xb))

array([[10., 11., 12.],
       [11., 19., 15.],
       [12., 15., 24.]])

In [46]:
np.dot(np.dot(np.linalg.inv((XbT.dot(Xb))), XbT),Y)

array([[1.],
       [2.],
       [3.]])

In [47]:
ds = np.array([[0,0,1]
              ,[1,0,3]
              ,[2,2,11]
              ,[0,1,4]
              ,[1,1,6]
              ,[2,3,14]
              ,[0,2,7]
              ,[1,2,9]
              ,[2,0,5]
              ,[2,1,8]])

In [49]:
X = ds[:, :-1]
X

array([[0, 0],
       [1, 0],
       [2, 2],
       [0, 1],
       [1, 1],
       [2, 3],
       [0, 2],
       [1, 2],
       [2, 0],
       [2, 1]])

In [50]:
Y = ds[:, -1:]
Y

array([[ 1],
       [ 3],
       [11],
       [ 4],
       [ 6],
       [14],
       [ 7],
       [ 9],
       [ 5],
       [ 8]])

In [51]:
Xb = np.hstack([np.ones([X.shape[0], 1]), X])
Xb

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 2.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 2., 3.],
       [1., 0., 2.],
       [1., 1., 2.],
       [1., 2., 0.],
       [1., 2., 1.]])

In [53]:
W = np.array([[0.3]
             ,[0.4]
             ,[0.5]])
W

array([[0.3],
       [0.4],
       [0.5]])

In [56]:
a = 0.1
a

0.1

In [57]:
Yhat = Xb.dot(W)
Yhat

array([[0.3],
       [0.7],
       [2.1],
       [0.8],
       [1.2],
       [2.6],
       [1.3],
       [1.7],
       [1.1],
       [1.6]])

In [58]:
S = np.dot(Xb.T, (Y - Yhat))
S

array([[54.6],
       [75.6],
       [92.4]])

In [59]:
W = W + (a/10)*S
W

array([[0.846],
       [1.156],
       [1.424]])