In [18]:
import numpy as np
import pandas as pd

In [5]:
ds = np.array([[0,0,1]
         ,[1,0,3]
         ,[2,2,11]
         ,[0,1,4]
         ,[1,1,6]
         ,[2,3,14]
         ,[0,2,7]
         ,[1,2,9]
         ,[2,0,5]
         ,[2,1,8]])

In [7]:
ds

array([[ 0,  0,  1],
       [ 1,  0,  3],
       [ 2,  2, 11],
       [ 0,  1,  4],
       [ 1,  1,  6],
       [ 2,  3, 14],
       [ 0,  2,  7],
       [ 1,  2,  9],
       [ 2,  0,  5],
       [ 2,  1,  8]])

In [9]:
ds_feature = ds[:,:-1]

In [11]:
ds_feature

array([[0, 0],
       [1, 0],
       [2, 2],
       [0, 1],
       [1, 1],
       [2, 3],
       [0, 2],
       [1, 2],
       [2, 0],
       [2, 1]])

In [16]:
ds_target = ds[:,-1:]

In [17]:
ds_target

array([[ 1],
       [ 3],
       [11],
       [ 4],
       [ 6],
       [14],
       [ 7],
       [ 9],
       [ 5],
       [ 8]])

In [74]:
np.ones([ds_feature.shape[0],1])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [75]:
np.hstack([ds_feature, np.ones([ds_feature.shape[0],1])])

array([[0., 0., 1.],
       [1., 0., 1.],
       [2., 2., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [2., 3., 1.],
       [0., 2., 1.],
       [1., 2., 1.],
       [2., 0., 1.],
       [2., 1., 1.]])

In [73]:
ds_feature_b = np.hstack([np.ones([ds_feature.shape[0],1]), ds_feature])

In [61]:
ds_feature_b

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 2.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 2., 3.],
       [1., 0., 2.],
       [1., 1., 2.],
       [1., 2., 0.],
       [1., 2., 1.]])

In [63]:
w = np.array([[0.1]
             ,[0.2]
             ,[0.3]])

In [70]:
XbTXb = (ds_feature_b.T).dot(ds_feature_b)

In [71]:
XbTXb

array([[10., 11., 12.],
       [11., 19., 15.],
       [12., 15., 24.]])

In [77]:
XbTXb_1 =np.linalg.inv(XbTXb)

In [78]:
XbTXb_1

array([[ 0.36666667, -0.13333333, -0.1       ],
       [-0.13333333,  0.15238095, -0.02857143],
       [-0.1       , -0.02857143,  0.10952381]])

In [81]:
XbTXb_XbTXb_1 = np.dot(XbTXb,XbTXb_1)
XbTXb_XbTXb_1

array([[ 1.00000000e+00, -1.52655666e-16,  2.22044605e-16],
       [-4.99600361e-16,  1.00000000e+00,  5.55111512e-17],
       [-4.44089210e-16,  1.38777878e-16,  1.00000000e+00]])