In [1]:
import numpy as np

In [40]:
np.array([[3,100,10]
         ,[6,60,4]
         ,[1,10,1]
         ,[4,0,7]
         ,[2,40,3]])

array([[  3, 100,  10],
       [  6,  60,   4],
       [  1,  10,   1],
       [  4,   0,   7],
       [  2,  40,   3]])

In [41]:
ds

array([[  3, 100,  10],
       [  6,  60,   4],
       [  1,  10,   1],
       [  4,   0,   7],
       [  2,  40,   3]])

In [42]:
ds.max(axis=0)

array([  6, 100,  10])

In [43]:
ds.min(axis=0)

array([1, 0, 1])

In [44]:
ds - ds.min(axis=0) 

array([[  2, 100,   9],
       [  5,  60,   3],
       [  0,  10,   0],
       [  3,   0,   6],
       [  1,  40,   2]])

In [45]:
 (ds.max(axis=0) - ds.min(axis=0))

array([  5, 100,   9])

In [46]:

(ds - ds.min(axis=0)) / (ds.max(axis=0) - ds.min(axis=0))

array([[0.4       , 1.        , 1.        ],
       [1.        , 0.6       , 0.33333333],
       [0.        , 0.1       , 0.        ],
       [0.6       , 0.        , 0.66666667],
       [0.2       , 0.4       , 0.22222222]])

In [47]:
(ds - ds.min(axis=0)) * (5)

array([[ 10, 500,  45],
       [ 25, 300,  15],
       [  0,  50,   0],
       [ 15,   0,  30],
       [  5, 200,  10]])

In [48]:
((ds - ds.min(axis=0)) * (4)) / (ds.max(axis=0) - ds.min(axis=0)) + 1

array([[2.6       , 5.        , 5.        ],
       [5.        , 3.4       , 2.33333333],
       [1.        , 1.4       , 1.        ],
       [3.4       , 1.        , 3.66666667],
       [1.8       , 2.6       , 1.88888889]])

In [55]:
ds.mean(axis=0)

array([ 3.2, 42. ,  5. ])

In [56]:
(ds - ds.mean(axis=0))/ (ds.max(axis=0) - ds.min(axis=0))

array([[-0.04      ,  0.58      ,  0.55555556],
       [ 0.56      ,  0.18      , -0.11111111],
       [-0.44      , -0.32      , -0.44444444],
       [ 0.16      , -0.42      ,  0.22222222],
       [-0.24      , -0.02      , -0.22222222]])

In [57]:
ds.std(axis=0)

array([ 1.72046505, 36.        ,  3.16227766])

In [59]:
(ds - ds.mean(axis=0))/ ds.std(axis=0)

array([[-0.11624764,  1.61111111,  1.58113883],
       [ 1.62746694,  0.5       , -0.31622777],
       [-1.27872403, -0.88888889, -1.26491106],
       [ 0.46499055, -1.16666667,  0.63245553],
       [-0.69748583, -0.05555556, -0.63245553]])

In [63]:
ds_sq = np.square(ds)

In [76]:
ds_sq_sum = ds_sq.sum(axis=0)

In [77]:
ds_sq.sum(axis=0)


array([   66, 15300,   175])

In [78]:
np.sqrt(ds_sq_sum)

array([  8.1240384 , 123.69316877,  13.22875656])

In [80]:
x__ = np.sqrt(ds_sq_sum)

In [82]:
x__

array([  8.1240384 , 123.69316877,  13.22875656])

In [85]:
ds/x__

array([[0.36927447, 0.80845208, 0.75592895],
       [0.73854895, 0.48507125, 0.30237158],
       [0.12309149, 0.08084521, 0.07559289],
       [0.49236596, 0.        , 0.52915026],
       [0.24618298, 0.32338083, 0.22677868]])

In [86]:
test = np.array([[0,70,-1]
         ,[3,-105,2]])

In [87]:
test/x__

array([[ 0.        ,  0.56591646, -0.07559289],
       [ 0.36927447, -0.84887469,  0.15118579]])