In [57]:
import numpy as np

In [58]:
X0 = np.array([[0.62,0.74,0.87],
               [0.92,0.67,0.77],
               [0.42,0.32,0.59],
               [0.09,0.51,0.68],
               [0.85,0.48,0.52]])

In [59]:
X0

array([[0.62, 0.74, 0.87],
       [0.92, 0.67, 0.77],
       [0.42, 0.32, 0.59],
       [0.09, 0.51, 0.68],
       [0.85, 0.48, 0.52]])

In [60]:
W1 = np.array([[0.92,0.98,0.39,0.95],
               [0.74,0.17,0.51,0.26],
               [0.23,0.96,0.07,0.61]])

In [61]:
B1 = np.array([0.18,0.00,0.93,0.14])

In [62]:
Z1 = X0.dot(W1)

In [63]:
Z1

array([[1.3181, 1.5686, 0.6801, 1.3121],
       [1.5193, 1.7547, 0.7544, 1.5179],
       [0.7589, 1.0324, 0.3683, 0.8421],
       [0.6166, 0.8277, 0.3428, 0.6329],
       [1.2568, 1.4138, 0.6127, 1.2495]])

In [64]:
Z1 = Z1 + B1

In [65]:
Z1

array([[1.4981, 1.5686, 1.6101, 1.4521],
       [1.6993, 1.7547, 1.6844, 1.6579],
       [0.9389, 1.0324, 1.2983, 0.9821],
       [0.7966, 0.8277, 1.2728, 0.7729],
       [1.4368, 1.4138, 1.5427, 1.3895]])

In [66]:
(np.exp(Z1) - np.exp(-Z1))

array([[4.24962743, 4.59158695, 4.80344391, 4.03799826],
       [5.28730552, 5.60875385, 5.2036607 , 5.05773919],
       [2.16610922, 2.4516453 , 3.39006867, 2.29553371],
       [1.76712766, 1.85099681, 3.29079053, 1.70436639],
       [3.96952404, 3.86833235, 4.46339863, 3.76364326]])

In [67]:
(np.exp(Z1) +np.exp(-Z1))

array([[4.69673646, 5.00826024, 5.20317916, 4.50615467],
       [5.65292842, 5.95467209, 5.57477216, 5.43881657],
       [2.94822475, 3.16394764, 3.93605965, 3.04458125],
       [2.66884622, 2.72510352, 3.85088331, 2.62771094],
       [4.44489832, 4.35476694, 4.89100474, 4.262043  ]])

In [68]:
X1 = (np.exp(Z1) - np.exp(-Z1)) /  (np.exp(Z1) + np.exp(-Z1))

In [69]:
X1

array([[0.90480432, 0.91680279, 0.92317481, 0.89610734],
       [0.93532151, 0.9419081 , 0.9334302 , 0.92993377],
       [0.73471645, 0.77486911, 0.86128488, 0.75397354],
       [0.66213169, 0.67923908, 0.85455472, 0.64861259],
       [0.89305171, 0.88829836, 0.91257295, 0.88306084]])

In [70]:
W2 = np.array([[-0.63,0.21],
               [0.93,-0.83],
               [0.67,-0.89],
               [0.89,0.28]])

In [71]:
B2 = np.array([[0.85,0.87]])

In [72]:
Z2 = X1.dot(W2)

In [73]:
Z2

array([[ 1.69866252, -1.14165293],
       [ 1.73976127, -1.15573763],
       [ 1.50585423, -1.04428186],
       [ 1.36436625, -1.00366296],
       [ 1.66084292, -1.11467968]])

In [74]:
Z2 = Z2 + B2

In [75]:
Z2

array([[ 2.54866252, -0.27165293],
       [ 2.58976127, -0.28573763],
       [ 2.35585423, -0.17428186],
       [ 2.21436625, -0.13366296],
       [ 2.51084292, -0.24467968]])

In [76]:
Z2[Z2 > 0] = Z2[Z2 >0]
Z2[Z2 < 0] *= 0.5
Z2

array([[ 2.54866252, -0.13582646],
       [ 2.58976127, -0.14286881],
       [ 2.35585423, -0.08714093],
       [ 2.21436625, -0.06683148],
       [ 2.51084292, -0.12233984]])

In [77]:
X2 = Z2

In [78]:
X2

array([[ 2.54866252, -0.13582646],
       [ 2.58976127, -0.14286881],
       [ 2.35585423, -0.08714093],
       [ 2.21436625, -0.06683148],
       [ 2.51084292, -0.12233984]])

In [79]:
W3 = np.array([[0.51,0.26,0.34],
               [0.48,0.17,0.87]])

In [80]:
B3 = np.array([[0.54,0.69,0.82]])

In [81]:
Z3 = X2.dot(W3)
Z3

array([[1.23462118, 0.63956176, 0.74837623],
       [1.25220122, 0.64905023, 0.75622296],
       [1.15965801, 0.59770814, 0.72517783],
       [1.09724768, 0.56437387, 0.69474114],
       [1.22180677, 0.63202139, 0.74725093]])

In [82]:
Z3 = Z3 + B3

In [83]:
Z3

array([[1.77462118, 1.32956176, 1.56837623],
       [1.79220122, 1.33905023, 1.57622296],
       [1.69965801, 1.28770814, 1.54517783],
       [1.63724768, 1.25437387, 1.51474114],
       [1.76180677, 1.32202139, 1.56725093]])

In [84]:
np.exp(-Z3)

array([[0.16954767, 0.26459319, 0.20838327],
       [0.16659306, 0.26209448, 0.20675454],
       [0.18274601, 0.27590239, 0.21327394],
       [0.19451467, 0.2852544 , 0.21986509],
       [0.1717343 , 0.26659586, 0.2086179 ]])

In [85]:
X3 = 1 / (1 + np.exp(-Z3))
X3

array([[0.85503142, 0.79076813, 0.827552  ],
       [0.85719694, 0.79233371, 0.82866893],
       [0.84549006, 0.78375902, 0.82421617],
       [0.83716008, 0.77805608, 0.81976278],
       [0.8534358 , 0.78951782, 0.82739135]])

In [86]:
W4 = np.array([[0.85],[0.19],[0.12]])

In [87]:
B4 = np.array([[0.66]])

In [88]:
Z4 = X3.dot(W4)
Z4

array([[0.97632889],
       [0.97860108],
       [0.96648671],
       [0.95778826],
       [0.97471578]])

In [89]:
Z4 = Z4 + B4
Z4

array([[1.63632889],
       [1.63860108],
       [1.62648671],
       [1.61778826],
       [1.63471578]])

In [90]:
X4 = Z4
X4[X4 <= 0] = 0

In [91]:
X4

array([[1.63632889],
       [1.63860108],
       [1.62648671],
       [1.61778826],
       [1.63471578]])