In [2]:
import numpy as np

In [15]:
def tanh(x):
    return (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))

In [52]:
def relu(x):
    return np.maximum(0,x)

In [3]:
x_ts_1 = np.array([[1.135,1.132]
                  ,[1.137,1.132]
                  ,[1.137,1.132]
                  ,[1.136,1.128]])

In [4]:
x_ts_2 = np.array([[1.138,1.133]
                  ,[1.136,1.132]
                  ,[1.137,1.132]
                  ,[1.137,1.132]])

In [5]:
x_ts_3 = np.array([[1.14,1.135]
                  ,[1.137,1.133]
                  ,[1.136,1.132]
                  ,[1.137,1.132]])

In [6]:
ws = np.array([[0.36,0.81,-1.31]
              ,[-0.29,2.38,0.06]])

In [7]:
us = np.array([[0.25,0.87,-0.53]
              ,[0.27,-0.07,-1.34]
              ,[-0.58,0.2,0.19]])

In [8]:
bs = np.array([[1.06,-1.27,0.23]])

In [18]:
x_ts_1.dot(ws)

array([[ 0.08032,  3.61351, -1.41893],
       [ 0.08104,  3.61513, -1.42155],
       [ 0.08104,  3.61513, -1.42155],
       [ 0.08184,  3.6048 , -1.42048]])

In [19]:
s1_ts_1 = x_ts_1.dot(ws) + bs

In [20]:
s1_ts_1 

array([[ 1.14032,  2.34351, -1.18893],
       [ 1.14104,  2.34513, -1.19155],
       [ 1.14104,  2.34513, -1.19155],
       [ 1.14184,  2.3348 , -1.19048]])

In [21]:
h1_ts_1 = tanh(s1_ts_1)

In [22]:
h1_ts_1

array([[ 0.81452182,  0.98174004, -0.83024673],
       [ 0.814764  ,  0.98179857, -0.83105897],
       [ 0.814764  ,  0.98179857, -0.83105897],
       [ 0.81503275,  0.98142215, -0.83072768]])

In [23]:
x_ts_2.dot(ws)

array([[ 0.08111,  3.61832, -1.4228 ],
       [ 0.08068,  3.61432, -1.42024],
       [ 0.08104,  3.61513, -1.42155],
       [ 0.08104,  3.61513, -1.42155]])

In [24]:
h1_ts_1.dot(us)

array([[ 0.95024337,  0.47386283, -1.9049751 ],
       [ 0.95079081,  0.47390698, -1.90533621],
       [ 0.95079081,  0.47390698, -1.90533621],
       [ 0.95056422,  0.47423341, -1.90491129]])

In [25]:
bs

array([[ 1.06, -1.27,  0.23]])

In [26]:
s1_ts_2 = x_ts_2.dot(ws) + h1_ts_1.dot(us) + bs

In [27]:
s1_ts_2

array([[ 2.09135337,  2.82218283, -3.0977751 ],
       [ 2.09147081,  2.81822698, -3.09557621],
       [ 2.09183081,  2.81903698, -3.09688621],
       [ 2.09160422,  2.81936341, -3.09646129]])

In [28]:
x_ts_2.dot(ws) + h1_ts_1.dot(us)

array([[ 1.03135337,  4.09218283, -3.3277751 ],
       [ 1.03147081,  4.08822698, -3.32557621],
       [ 1.03183081,  4.08903698, -3.32688621],
       [ 1.03160422,  4.08936341, -3.32646129]])

In [29]:
h1_ts_2 = tanh(s1_ts_2)

In [30]:
h1_ts_2

array([[ 0.96994426,  0.99295015, -0.99593133],
       [ 0.96995121,  0.99289436, -0.99591344],
       [ 0.96997251,  0.99290582, -0.99592411],
       [ 0.9699591 ,  0.99291043, -0.99592065]])

In [31]:
x_ts_3.dot(ws)

array([[ 0.08125,  3.6247 , -1.4253 ],
       [ 0.08075,  3.61751, -1.42149],
       [ 0.08068,  3.61432, -1.42024],
       [ 0.08104,  3.61513, -1.42155]])

In [32]:
h1_ts_2.dot(us)

array([[ 1.08822278,  0.57515873, -2.03385062],
       [ 1.08819907,  0.57517226, -2.03377613],
       [ 1.08821368,  0.57518786, -2.03380481],
       [ 1.08820957,  0.57517656, -2.03380323]])

In [33]:
bs

array([[ 1.06, -1.27,  0.23]])

In [34]:
x_ts_3.dot(ws) + h1_ts_2.dot(us)

array([[ 1.16947278,  4.19985873, -3.45915062],
       [ 1.16894907,  4.19268226, -3.45526613],
       [ 1.16889368,  4.18950786, -3.45404481],
       [ 1.16924957,  4.19030656, -3.45535323]])

In [35]:
s1_ts_3 = x_ts_3.dot(ws) + h1_ts_2.dot(us) + bs

In [36]:
s1_ts_3

array([[ 2.22947278,  2.92985873, -3.22915062],
       [ 2.22894907,  2.92268226, -3.22526613],
       [ 2.22889368,  2.91950786, -3.22404481],
       [ 2.22924957,  2.92030656, -3.22535323]])

In [37]:
h1_ts_3 = tanh(s1_ts_3)

In [38]:
h1_ts_3

array([[ 0.97711575,  0.99431212, -0.99686999],
       [ 0.97709204,  0.99423013, -0.99684562],
       [ 0.97708954,  0.99419349, -0.99683792],
       [ 0.97710565,  0.99420273, -0.99684617]])

In [39]:
uy = np.array([[-0.7]
              ,[-1.03]
              ,[1.48]])

In [40]:
uy

array([[-0.7 ],
       [-1.03],
       [ 1.48]])

In [41]:
by = np.array([[-0.95]])

In [42]:
by

array([[-0.95]])

In [43]:
h1_ts_3.dot(uy)

array([[-3.1834901 ],
       [-3.18335299],
       [-3.18330209],
       [-3.1833351 ]])

In [44]:
s2_ts_3 = h1_ts_3.dot(uy) + by

In [45]:
s2_ts_3

array([[-4.1334901 ],
       [-4.13335299],
       [-4.13330209],
       [-4.1333351 ]])

In [53]:
yhat = relu(s2_ts_3)

In [54]:
yhat

array([[0.],
       [0.],
       [0.],
       [0.]])